# Generated by Django 3.0.3 on 2020-03-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200308_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/DJI_0335.JPG', upload_to='images/'),
        ),
    ]
