# Generated by Django 3.0.3 on 2020-03-09 19:22

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200309_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(default='images/DJI_0335.JPG', upload_to='images/'),
        ),
    ]
