# Generated by Django 3.0.3 on 2020-03-09 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200309_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='images/DJI_0335.JPG', upload_to='images/'),
        ),
    ]
